site_name: Lichess
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    primary: grey
  features:
    - tabs
    - navigation.section
nav:
  - Home: index.md
  - Atas:
      - 01/11/2022: "atas/ata_01_11.md"
      - 10/11/2022: "atas/ata_10_11.md"
      - 15/11/2022: "atas/ata_15_11.md"
      - 22/11/2022: "atas/ata_22_11.md"
  - Planejamento:
      - Cronograma: "planejamento/cronograma.md"
      - Cronograma Realizado: "planejamento/cronograma_realizado.md"
      - Ferramentas: "planejamento/tools.md"
      - Metodologia: "planejamento/metodologias.md"
      - Sítios avaliados: "planejamento/sites_avaliados.md"
      - Avaliação dos sites:
          - Resultados TSE: "planejamento/sítios_avaliados/resultados_tse.md"
          - Resultados Age Telecom: "planejamento/sítios_avaliados/resultados_age_telecom.md"
          - Resultados Lichess: "planejamento/sítios_avaliados/resultados_lichess.pdf"
      - Sítio selecionado: "planejamento/app_selected.md"
      - Processo de Design: "planejamento/processo_de_design.md"
  - Análise de Requisitos:
      - Aspectos éticos: "analise_requisitos/aspectos_eticos.md"
      - Análise de tarefas: "analise_requisitos/analise_tarefas.md"
      - Perfil de Usuário: "analise_requisitos/perfil_usuario.md"
      - Personas: "analise_requisitos/personas.md"
  - Apresentações: "apresentacoes.md"

  # - Nova navegação: "nome do arquivo relativo a docs"
  # - Nova navegação:
  #   - Navegação com filhos: "nome do arquivo relativo a docs"
