site_name: Grupo 02
theme:
  name: material
  features:
    - tabs
    - navigation.section
nav:
  - "Home": index.md
  - "About Us": "about_us.md"
  - "Atas":
    - "01/11/2022": "atas/ata_01_11.md"
  # - "Nova navegação": "nome do arquivo relativo a docs"
  # - "Nova navegação":
  #   - "Navegação com filhos": "nome do arquivo relativo a docs"
    