site_name: Lichess

repo_name: "2022.2-Lichess"
repo_url: "https://github.com/Interacao-Humano-Computador/2022.2-Lichess"

copyright: "Copyright &copy; 2022 Lichess"

theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Tema escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Tema claro
  features:
    - tabs
    - navigation.section
nav:
  - Home: index.md
  - Atas:
      - 01/11/2022: "atas/ata_01_11.md"
      - 10/11/2022: "atas/ata_10_11.md"
      - 15/11/2022: "atas/ata_15_11.md"
      - 22/11/2022: "atas/ata_22_11.md"
      - 29/11/2022: "atas/ata_29_11.md"
      - 06/12/2022: "atas/ata_06_12.md"
  - Planejamento:
      - Cronograma: "planejamento/cronograma.md"
      - Cronograma Realizado: "planejamento/cronograma_realizado.md"
      - Ferramentas: "planejamento/tools.md"
      - Metodologia: "planejamento/metodologias.md"
      - Sítios avaliados: "planejamento/sites_avaliados.md"
      - Avaliação dos sítios:
          - Resultados TSE: "planejamento/sítios_avaliados/resultados_tse.md"
          - Resultados Age Telecom: "planejamento/sítios_avaliados/resultados_age_telecom.md"
          - Resultados Lichess: "planejamento/sítios_avaliados/resultados_lichess.pdf"
      - Sítio selecionado: "planejamento/app_selected.md"
      - Processo de Design: "planejamento/processo_de_design.md"
  - Análise de Requisitos:
      - Aspectos éticos: "analise_requisitos/aspectos_eticos.md"
      - Princípios Gerais do Projeto: "analise_requisitos/principios_gerais.md"
      - Perfil de Usuário: "analise_requisitos/perfil_usuario.md"
      - Personas: "analise_requisitos/personas.md"
      - Metas de Usabilidade: "analise_requisitos/metas_usabilidade.md"
      - Mapa de Empatia: "analise_requisitos/mapa_empatia.md"
      - Análise de tarefas: "analise_requisitos/analise_tarefas.md"
      - Guia de Estilo: "analise_requisitos/guia_de_estilo.md"
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
          - Storyboard:
              - Planejamento da Avaliação: design_avaliacao_desenvolvimento/nivel_1/storyboard/planejamento_avaliacao.md
              - Planejamento do Relato de Resultados: design_avaliacao_desenvolvimento/nivel_1/storyboard/planejamento_relato.md
          - Análise de tarefas:
              - Planejamento do Relato de Resultados: "design_avaliacao_desenvolvimento/nivel_1/analise_tarefas/planejamento_resultado_analise_tarefas.md"
  - Apresentações: "apresentacoes.md"

  # - Nova navegação: "nome do arquivo relativo a docs"
  # - Nova navegação:
  #   - Navegação com filhos: "nome do arquivo relativo a docs"
